//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ai_Accessories.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string Flag { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<bool> IsParent { get; set; }
    }
}
