//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ai_Accessories.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int Id { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> Gia { get; set; }
        public string HinhanhSP { get; set; }
        public Nullable<bool> Conhang { get; set; }
        public string ThongtinSP { get; set; }
        public Nullable<int> LoaiSP { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
        public Nullable<int> Solanmua { get; set; }
    
        public virtual LOAISP LOAISP1 { get; set; }
    }
}
