CREATE TABLE [dbo].[CHITIETDONHANG] (
    [MaDonHang] INT NOT NULL,
    [Masp]      INT NOT NULL,
    [Soluong]   INT NULL,
    [Dongia]    INT NULL,
    CONSTRAINT [PK_CHITIETDONHANG] PRIMARY KEY CLUSTERED ([MaDonHang] ASC, [Masp] ASC),
    CONSTRAINT [FK_CHITIETDONHANG_DONDATHANG] FOREIGN KEY ([MaDonHang]) REFERENCES [dbo].[DONDATHANG] ([MaDonHang]),
    CONSTRAINT [FK_CHITIETDONHANG_SANPHAM] FOREIGN KEY ([Masp]) REFERENCES [dbo].[SANPHAM] ([Id])
);



